engines:
  eslint:
    enabled: true
  checks:
    import/extensions:
      enabled: false
    no-multiple-empty-lines:
      enabled: true
    linebreak-style:
      enabled: true
  duplication:
    enabled: true
  config:
    languages:
      - javascript
ratings:
  paths:
  - "server/*.js"
  - "server/app/**/*.js"
exclude_paths:
- server/test/
- client/__test__
- dist