engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
  - "server/*.js"
  - "server/app/**/*.js"
exclude_paths:
- server/test/
- client/__test__/
- dist/
- coverage
- node_modules