language: node_js
node_js: 
  - '6'
before_install: 
  - travis_wait npm install
cache: 
  - node_modules
script:
  - npm run test:api
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info



