
const PostItConstants = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  SIGN_OUT: 'SIGN_OUT',
  CREATE_GROUP: 'CREATE_GROUP',
  ADD_MEMBERS: 'ADD_MEMBERS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  VIEW_MESSAGE: 'VIEW_MESSAGE',
  RESET_PASSWORD: 'RESET_PASSWORD',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER_ERROR: 'REGISTER_ERROR'


};

export default PostItConstants;